---
- name: "Install pyOpenSSL"
  package:
    name: "pyOpenSSL"

- name: "Create dirs"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ le_cert_home }}"
    - "{{ le_csr_home }}"
    - "{{ (le_payload_root | dirname) ~ '/.well-known/acme-challenge' }}"
    - "{{ le_shared_key | dirname }}"
    - "{{ le_account_key | dirname }}"

- name: Generate dhparam
  command: openssl dhparam -out {{ le_dhparam }} 2048
    creates='{{ le_dhparam }}'

- name: "Download Intermediate Certificate - Let’s Encrypt Authority X3 (IdenTrust cross-signed)"
  get_url:
    url: https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt
    dest: "{{ le_cert_home }}le_inter.pem"

- name: "Create account key"
  openssl_privatekey:
    path: "{{ le_account_key }}"

- name: "Create shared key"
  openssl_privatekey:
    path: "{{ le_shared_key }}"

- name: "Run Lets Encrypt Challenge"
  include_tasks: "le_challenge.yml"
  with_items: "{{ le_domains }}"
  loop_control:
    loop_var: domain
